### ISSUE TITLE
$ ./rust-invaders.exe wgpu error: Validation Error  Caused by:     In Device::create_texture     Dimension X is zero

### ISSUE THREAD

**Issue by ltp456** [jeremychone-channel/rust-invaders#2] opened 2021-08-08 05:14 UTC
I am a new player, there is an error;

`
`$ ./rust-invaders.exe
wgpu error: Validation Error
Caused by:
    In Device::create_texture
    Dimension X is zero

**Comment by sunwukonga** [comment] 2021-10-16 02:03
Can you describe your steps to reproduce the problem?

For instance, I did the following and had no problem:
```
cargo build --release
cd target/release
ln -s ../../assets ./assets
./rust-invaders
```
Using `origin/main` at commit `58766b9`. Current HEAD.

`rustup show` gives
```
active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.57.0-nightly (e1e9319d9 2021-10-14)
```
`Linux archlinux 5.13.0-rc3-1-drm-tip-git-g7f5eac3354e9 #1 SMP PREEMPT Sun, 30 May 2021 10:38:23 +0000 x86_64 GNU/Linux`
`Two core Intel(R) Pentium(R) CPU G3420 @ 3.20GHz`
Onboard gfx: `VGA compatible controller: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller (rev 06)`

Seems to be a known problem with Windows: https://github.com/bevyengine/bevy/issues/2299

**Comment by jeremychone** [comment] 2022-01-29 04:43
@abortrao Can you let me know if you still get the issue with the latest main branch (I updated to bevy v0.6 with edition 2021). So, those issues might be fixed now.

**Closed as completed** 2022-02-07 06:35 UTC
